### ISSUE TITLE
Compatible with SourceJS 0.5.6?

### ISSUE THREAD

**Issue by maskott** [ashmigelski/sourcejs-skins-viewer#1]
Hello!  I've been looking into SourceJS and using it with several custom stylesheets. I found an old thread where it looked like you were doing almost the exact same thing. I've been trying to install this `sourcejs-skins-viewer` and am having some trouble. I'm wondering if this repo has gone stale, or if it should be still compatible with the most recent SourceJS? Any insight you might be able to provide would be greatly appreciated. Thanks!

**Comment by ashmigelski** [comment]
Hello!
This plugin compatible with SourceJS 0.4.0.
I'll try to adapt it to new 0.5.6 version and write here about results

**Comment by ashmigelski** [comment]
Ok, it was pretty easy https://github.com/ashmigelski/sourcejs-skins-viewer/commit/4a9110620a830c68058a8464a173090f34754b86

For testing I recommend you to do following:
- create new user folder like `./sourcejs/skins-viewer/`
- clone sourcejs-skins-viewer project into it
- open `./sourcejs/options.js` and change `pathToUser: 'user'` to `pathToUser: 'skins-viewer'`
- restart SourceJS and visit it in browser

Hope this helps)

**Comment by maskott** [comment]
Thank you very much! I really appreciate you updating this repo. I think we are trying to do something similar to what you have done, but not the exact same. It took me most of the day looking at your code, but I think I understand enough of how it works to get our version going. Thanks again!

**Comment by ashmigelski** [comment]
Was glad to help
